## Server Configuration
#server:
#  port: 8090
#
## DataSource Configuration
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydatabase
#    username: root
#    password: secret
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#
## Logging Configuration
#logging:
#  level:
#    org.springframework: INFO
#    com.myapp: DEBUG
#
## Spring Profiles
#spring:
#  profiles:
#    active: local
#
## Custom Properties
#app:
#  name: My Spring Boot Application
#  description: This is a sample Spring Boot application.
